services:
  - type: worker
    name: ph-downloader
    env: python
    repo: https://github.com/USERNAME/ph_downloader_bot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
